# -*- coding: utf-8 -*-
"""divisible.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fH2Ej9C4eJ3GUPVrGaOPaRdAF368AMCd
"""



# Commented out IPython magic to ensure Python compatibility.
# %%writefile div.py
# def divisiable_by_5(list1):
#     print("Given list",list1)
#     if list1 % 5==0:    
#         print(list1)      
# x=[5,12,14,18,20,25,10]
# print("The list is",divisiable_by_5(x))