# -*- coding: utf-8 -*-
"""index.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19C8Zww0lwBIfq-0OsijsGo2GgVPMu-Rp
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile index.py
# print("enter text to print::")
# inputchars = input()
# 
# if inputchars:
# 	string = ""
# 	for i in inputchars:
# 		if inputchars.index(i)%2 == 0:
# 			string += str(i)
# 	
# 	print('-------------------')
# 	print("You Entered:", inputchars)
# 	print("Result:")
# 	print(string)