# -*- coding: utf-8 -*-
"""iterate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SuN9kDkNDMGob7f22YEkYM10M6ppG_PH
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile iterate.py
# print("Printing current and previous number and their sum in a range(10)")
# previous_num = 0
# 
# # loop from 1 to 10
# for i in range(1, 11):
#     x_sum = previous_num + i
#     print("Current Number", i, "Previous Number ", previous_num, " Sum: ", previous_num + i)
#     # modify previous number
#     # set it to the current number
#     previous_num = i
#