# -*- coding: utf-8 -*-
"""palindrome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OBsSrhC8mI4Yy8qOb4XPIxM1owGmshR0
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile palindrome.py
# n=int(input("Enter  a number:"))
# temp=n
# rev=0
# while(n>0):
#     dig=n%10
#     rev=rev*10+dig
#     n=n//10
# if(temp==rev):
#     print("The number is a palindrome!")
# else:
#     print("The number isn't a palindrome!")