# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bG48GnS4CgESlb9yXKjnvaZC5Byf4cH3
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile reverse.py
# num = int(input("Enter a number with multiple digit: "))
# n=0
# while num>0:
#     a = num%10
#     num = num - a
#     num = num/10
#     print(int(a),end="")
#     n = n + 1   
# print(n)