# -*- coding: utf-8 -*-
"""table.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rpF4F2tKu6cA02JW1KDZNaDCx-YvjgIr
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile script.py
# #multiplication
# num = int(input('table you want to write  here:'))
# 
# starting_range = int(input('write the number from where to start:'))
# ending_range = int(input('write the end of the number you need:'))
# print()
# print(' here is the table of', num)
# for i in range(starting_range, ending_range + 1):
#    print(num, 'x', i, '=', num*i)